version: '3.8'

services:
  app:
    build: .
    container_name: apiorder_app
    volumes:
      - .:/var/www
    networks:
      - laravel_net

  web:
    image: nginx:alpine
    container_name: apiorder_web
    volumes:
      - .:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - app
    networks:
      - laravel_net

  # 目前不需要
  # db:
  #   image: mysql:8
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root
  #     MYSQL_DATABASE: laravel
  #     MYSQL_USER: laravel
  #     MYSQL_PASSWORD: secret
  #   volumes:
  #     - dbdata:/var/lib/mysql
  #   networks:
  #     - laravel_net

volumes:
  dbdata:

networks:
  default:
    driver: bridge
  laravel_net:
